# Generated by Django 4.2.4 on 2023-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='image',
            field=models.CharField(default='https://www.idsplus.net/wp-content/uploads/default-placeholder-300x300.png', max_length=150),
        ),
    ]
